services:
  - type: web
    name: gengas-garden
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    envVars:
      - key: NODE_VERSION
        value: 18
    staticPublishPath: dist
